files/root_bashrc, tasks/jboss-set-ci-scripts.yml
This change already lives on Thunder - now it is tracked.
=> add path to 'ops' scripts to root bashrc

tasks/os-config.yml
Fix issue https://github.com/jboss-set/zeus/issues/5
=> Add a check to ensure /usr/share attributes are corrects

files/prbz-overview.payload.properties
add new eap6413-payload and eap704-payload
update here first, I will update the same file on thunder after this is merged.
=> Add eap6413-payload and eap704-payload

files/prbz-overview.payload.properties
I will update the same file on thunder once this is merged. Thanks
=> add eap705-payload

hosts.yml, tasks/tools.yml
just to keep track of Bartosz's installation of cloc on Thunder.
=> add cloc to installed tools

files/prbz-overview.payload.properties
add new EAP 6.4.14 payload link per https://bugzilla.redhat.com/show_bug.cgi?id=1401452
I will update the same file on thunder once this is merged. Thanks.
=> add new eap6414-payload

files/prbz-overview.payload.properties
add new eap6415-payload https://bugzilla.redhat.com/show_bug.cgi?id=1419353
=> add eap6415-payload.

hosts.yml
Could you please add account: `lgao` to the sudoers list? Thank you!
=> Add lgao to the sudoers file

hosts.yml, tasks/nginx.yml, templates/nginx.conf.j2
Issue: https://projects.engineering.redhat.com/browse/SET-23
=> SET-23 Set up a HTTP proxy cache for Maven Central on Thunder

tasks/nginx.yml, templates/jboss-set-index.html.j2, templates/nginx.conf.j2
The CSS stuff could be extracted to external file. Not sure if it's worth the effort though...
=> Adding index page for nginx

hosts.yml, tasks/monit.yml, templates/check-sudoers-list.j2
@rpelisse that's one way I think we can ensure only valid sudoers are on the list. The downside is the tmp folder will be created and deleted every run
=> Adding a check to make sure only allowed users are in sudoers list

tasks/java_cert.yml, tasks/java_certs.yml, zeus.yml
https://projects.engineering.redhat.com/browse/SET-125
@spyrkob can you take a look, see if you like the approach?
=> Deploy internal server certificate to allow Jenkins job to access unverified HTTPS endpoints

tasks/maven.yml, templates/harmonia-eap-build.j2
@spyrkob Let me know what you think!
=> Add harmonia-build into Zeus

templates/aphrodite.json.j2, templates/prbz-overview.aphrodite.properties.json.j2
As part of https://projects.engineering.redhat.com/browse/SET-195 I have to update the url in the configuration files.
FYI @rpelisse
=> update url to https://issues.redhat.com/

roles/monit/templates/check-pg-container.j2, tasks/docker.yml
Issue: https://projects.engineering.redhat.com/browse/SET-235
Sets up a docker volume and container running postgresql as well as monit script to monitor it.
=> [SET-235] Set up postgresql docker container

templates/nginx.conf.j2
@rpelisse could you take a look please?
=> Redirect mjolnir to openshift instance

roles/monit/tasks/main.yml, roles/monit/templates/check-pg-container.j2
Issue: https://projects.engineering.redhat.com/browse/SET-235
=> [SET-235] Install docker monitoring script

tasks/pull-request-processor.yml, templates/aphrodite.json.j2, templates/prbz-overview.aphrodite.properties.json.j2, templates/pull-request-processor.j2
@spyrkob for you to review and approve when you are back!
=> [SET-294]  Pull Request Processor no longer under Ansible control

tasks/disabled.yml, tasks/jboss-set-ci-scripts.yml, tasks/jenkins.yml, tasks/kdump.yml, tasks/ntp.yml, tasks/os-config.yml, tasks/repos.yml, tasks/sshd.yml, tasks/sudoers.yml, tasks/sysctl.yml, tasks/tuned-adm.yml
@spyrkob To approve and merge last, it's not really important
=> Format files to follow Ansible prefered syntax

roles/monit/tasks/main.yml
@spyrkob One more cleanup / enhancement on Zeus for you to approve!
=> Monit cleanup

tasks/docker.yml, tasks/jboss-eap7.yml, templates/jboss-set-404.html.j2, templates/nginx.conf.j2, zeus.yml
=> SET-303 Update JCliff configuration to define interfaces and ports

templates/prbz-overview.aphrodite.properties.json.j2, templates/pull-request-processor.j2
Next pull-request-processor will depend on a new Aphrodite version with Gitlab implementation, so this is to add gitlab configuration. 
Please just review and approve, I will make the actual version upgrade and configuration change on Thunder. Thanks.
=> Add gitlab configuration for pull-request-processor

roles/old_releases/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-385
=> [SET-385] Install jboss-eap-7.4.0.zip to old-releases directory

roles/netrc/tasks/main.yml, roles/netrc/templates/netrc.j2, zeus.yml
@gaol please review, comment and/or approve!
=> add netrc role

roles/jenkins/templates/casc.yaml.j2
Issue: https://github.com/jboss-set/zeus/issues/95
=> [ISSUE_95] Add label in default view for cryo

roles/jenkins/defaults/main.yml, roles/nginx/tasks/http_cache_setup.yml, roles/nginx/templates/commons.d/sites.conf.j2, roles/nginx/templates/index.html.j2, roles/nginx/templates/settings-64.xml.j2
@rpelisse @spyrkob @gaol This is the other part of setting up the HTTP caches for EAP 6.4 builds.
=> jobs: Integrate HTTP caches & create Maven settings for EAP 6.4 builds

roles/component_alignment/tasks/main.yml, roles/component_alignment/templates/smtp-settings.sh.j2
Adding a rule that should create a parametrized settings file for dependency alignment script.
Cc @rpelisse @spyrkob
=> Dependency alignment: create a config file with SMTP URL

roles/pgsql/tasks/deploy/db.yml
https://issues.redhat.com/browse/SET-410
Hide false changed results in check-mode
=> [SET-410] skip get_url task in check mode

roles/nginx/handlers/main.yml, roles/nginx/tasks/http_cache_setup.yml, roles/nginx/tasks/nginx_config.yml, roles/nginx/tasks/ssl.yml
@rpelisse @spyrkob am I correct to think that this should cause nginx to be restarted when some tasks cause modifications?
=> nginx: add handler to restart nginx when configuration changes

roles/payload_status/handlers/main.yml
Renaming the image name as per https://github.com/jboss-set/ares/tree/olympus
=> Replace the wrong image name.

tasks/docker.yml
The DB was migrated to Olympus.
=> Remove containerized postgres database

cci_worker.yml, roles/cci_account/defaults/main.yml, roles/cci_account/tasks/main.yml, roles/sudoers/defaults/main.yml, roles/sudoers/tasks/main.yml, roles/sudoers/templates/sudo.conf.j2
Issue: https://issues.redhat.com/browse/SET-139
=> SET-139 Automate CCI VMs setup with Ansible.

roles/monit/defaults/main.yml, roles/podman/defaults/main.yml
=> podman: add image for Ansible build

roles/jobs/defaults/main.yml, roles/monit/handlers/main.yml, roles/monit/tasks/setup.yml
option to disable monit and jenkins jobs in local env
=> Disable monit in local env

roles/jenkins/templates/casc.yaml.j2
@spyrkob What do you think? Seems simple enough.
=> jenkins: add env vars

roles/java_certs/tasks/java_certs.yml, roles/jenkins/defaults/main.yml, roles/jobs/templates/job-template.yml.j2
Part of https://projects.engineering.redhat.com/browse/SET-422
Install JDK17 and enable to create testsuite job: allow to override the parent_jobname, add jdk paths to config
=> Install JDK17 and setup eap-7.4.x jdk17 test job

roles/jenkins/defaults/main.yml, roles/jenkins/templates/casc.yaml.j2
https://issues.redhat.com/browse/SET-411
Part of https://github.com/jboss-set/cedalion/pull/16
=> Removing streams

roles/java/tasks/java_tools_setup.yml, roles/jenkins/defaults/main.yml, roles/jenkins/tasks/generate_keys.yml, roles/jenkins/tasks/jenkins_next.yml, roles/jenkins/tasks/main.yml, roles/jenkins/templates/casc.yaml.j2, roles/monit/defaults/main.yml, roles/nginx/tasks/jenkins.yml, roles/nginx/tasks/main.yml, roles/nginx/templates/commons.d/jenkins.conf.j2, roles/nginx/templates/commons.d/sites.conf.j2, roles/podman/defaults/main.yml
@spyrkob just for a quick review, this has already been deployed and tested.
=> Jenkins.next infrastructure

roles/cci_account/tasks/main.yml
@rpelisse can you review please?
=> Install ssh key for CCI Jenkins account

molecule/motd/verify.yml
Issue: https://issues.redhat.com/browse/SET-471
=> SET-471 motd role - molecule refactor into Molecule testsuite.

molecule/bashrc/converge.yml, molecule/bashrc/molecule.yml, molecule/bashrc/verify.yml
Issue: https://issues.redhat.com/browse/SET-473
=> SET-473 bashrc role - molecule refactor into Molecule testsuite.

molecule/git/converge.yml, molecule/git/molecule.yml, molecule/git/prepare.yml, molecule/git/vars.yml, molecule/git/verify.yml
Issue: https://issues.redhat.com/browse/SET-476
=> SET-476 git role - molecule refactor into Molecule testsuite.

molecule/sysctl/converge.yml, molecule/sysctl/molecule.yml, molecule/sysctl/vars.yml, molecule/sysctl/verify.yml
Issue: https://issues.redhat.com/browse/SET-482
=> SET-482 motd sysctl - molecule refactor into Molecule testsuite.

molecule/netrc/converge.yml, molecule/netrc/molecule.yml, molecule/netrc/prepare.yml, molecule/netrc/vars.yml, molecule/netrc/verify.yml
Issue: https://issues.redhat.com/browse/SET-490
=> SET-490 netrc - molecule refactor into Molecule testsuite.

roles/jenkins/templates/casc.yaml.j2
=> Remove unused "Component Alignment" jenkins folder

molecule/kdump/converge.yml, molecule/kdump/molecule.yml, molecule/kdump/vars.yml, molecule/kdump/verify.yml
Issue: https://issues.redhat.com/browse/SET-495
=> SET-495 kdump role - molecule refactor into Molecule testsuite

molecule/cron/converge.yml, molecule/cron/molecule.yml, molecule/cron/prepare.yml, molecule/cron/vars.yml, molecule/cron/verify.yml
Issue: https://issues.redhat.com/browse/SET-499
=> SET-499 cron role - molecule refactor into Molecule testsuite.

molecule/bashrc/converge.yml, molecule/bashrc/verify.yml, molecule/cron/prepare.yml, molecule/fast_yum_install/converge.yml, molecule/fast_yum_install/verify.yml, molecule/git/prepare.yml, molecule/git/verify.yml, molecule/java/converge.yml, molecule/java/prepare.yml, molecule/java/verify.yml, molecule/kdump/converge.yml, molecule/kdump/verify.yml, molecule/motd/converge.yml, molecule/motd/prepare.yml, molecule/motd/verify.yml, molecule/netrc/converge.yml, molecule/netrc/prepare.yml, molecule/netrc/verify.yml, molecule/prepare.yml, molecule/sysctl/verify.yml
Issue: https://issues.redhat.com/browse/SET-466
(Updating few leftover places in molecule)
=> SET-466 Zeus - Update molecule playbooks for Ansible 2.12 compliance.

molecule/hosts/converge.yml, molecule/hosts/molecule.yml, molecule/hosts/prepare.yml, molecule/hosts/vars.yml, molecule/hosts/verify.yml, roles/hosts/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-512
=> SET-512 hosts role - molecule refactor into Molecule testsuite.

molecule/account/converge.yml, molecule/account/molecule.yml, molecule/account/vars.yml, molecule/account/verify.yml, roles/account/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-514
=> SET-514 account role - molecule refactor into Molecule testsuite.

molecule/aphrodite/converge.yml, molecule/aphrodite/molecule.yml, molecule/aphrodite/prepare.yml, molecule/aphrodite/vars.yml, molecule/aphrodite/verify.yml
Issue: https://issues.redhat.com/browse/SET-515
=> SET-515 aphrodite role - molecule refactor into Molecule testsuite.

molecule/account/molecule.yml, molecule/aphrodite/molecule.yml, molecule/bashrc/molecule.yml, molecule/cron/molecule.yml, molecule/fast_yum_install/molecule.yml, molecule/git/molecule.yml, molecule/hosts/molecule.yml, molecule/java/molecule.yml, molecule/kdump/molecule.yml, molecule/motd/molecule.yml, molecule/netrc/molecule.yml, molecule/qualys_fix/molecule.yml
This will fixup the issue with a GH Action CI along with implementing proper testing for all scenarios.
=> Update all molecule scenario configuration to use scenarios

roles/jenkins/tasks/main.yml, roles/nginx/tasks/main.yml, roles/pgsql/tasks/main.yml, roles/pgsql/vars/main.yml
=> SET-552 - Zeus breaks with Ansible 2.13

roles/ares/defaults/main.yml
=> ares: switch default branch to main

roles/monit/defaults/main.yml, roles/monit/templates/dnf-needs-restarting.sh.j2
=> monit: add alert if server needs restart to apply update

cci_worker.yml, roles/cci_worker/tasks/main.yml, roles/sshd/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-557
=> SET-557 CCI Docker environment missing.

cci_worker.yml, roles/cci_worker/tasks/main.yml, roles/java/tasks/archive_tool_install.yml, roles/java/tasks/main.yml, roles/sshd/tasks/main.yml
@spyrkob here is the change for the old jdk, but also a commit from Ranabir about CCI that is on Olympus... Do we keep it?
=> Rm old jdk

cci_worker.yml, roles/cci_worker/tasks/main.yml, roles/jenkins/templates/casc.yaml.j2, roles/jenkins/vars/main.yml, roles/sshd/tasks/main.yml
@rpelisse a couple commits ended up on olympus branch rather than main. I assume that's a mistake?
=> Sync main branch with olympus changes

.ansible-lint, .github/workflows/ci.yml, molecule/account/molecule.yml, molecule/aphrodite/molecule.yml, molecule/bashrc/molecule.yml, molecule/cron/molecule.yml, molecule/fast_yum_install/molecule.yml, molecule/git/molecule.yml, molecule/hosts/molecule.yml, molecule/java/molecule.yml, molecule/kdump/molecule.yml, molecule/motd/molecule.yml, molecule/netrc/molecule.yml, molecule/qualys_fix/molecule.yml, roles/payload_status/tasks/deploy_website.yml
Issue: https://issues.redhat.com/browse/SET-573
=> SET-573 Fixing podman driver of molecule test for GitHub CI

roles/jenkins/templates/casc.yaml.j2
Issue: https://issues.redhat.com/browse/SET-601
=> SET-601 Olympus - Update CASC syntax for assignments

load_secrets.yml, molecule/vault/prepare.yml, roles/fast_yum_install/tasks/main.yml, roles/jenkins/defaults/main.yml, roles/monit/defaults/main.yml, roles/monit/vars/main.yml, roles/podman/tasks/setup.yml, roles/vault/defaults/main.yml, roles/vault/tasks/main.yml, roles/vault/tasks/vault-token.yml, zeus.yml
@spyrkob Following the integration of Vault, I did a few cleanups. Nothing big, but note that reviewing by commit might be easier than with files changes.
=> Zeus cleanup

roles/cci_worker/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-708
zeus-vars PR: https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/111
=> SET-708 Install RH CA on CCI VMs

cci_vm_automate.yml, cci_worker.yml
Issue: https://issues.redhat.com/browse/SET-721
=> SET-721 Refactor CCI automation in zeus

roles/monit/tasks/main.yml, roles/zeus_cronjobs/defaults/main.yml, tasks/jboss-eap7.yml, zeus.yml
https://issues.redhat.com/browse/SET-736
=> Disable docker and EAP
