hosts.yml
If accepted this changes requires to release and update [jboss-set-ci-scripts](https://github.com/rpelisse/hebe) 1.2.4, so that the scripts [dead-jbossas](https://github.com/rpelisse/hebe/commit/8dc2e4b9c0f4d56fc7ada24237b585e85c9d3cbf) is available.
Note that this change already lives on Thunder (the check is available), but it is not tracked by this project, and the script lives (untracked) in /root.
Also note that this PR depends on PR https://github.com/jboss-set/zeus/pull/4
=> Add monit check to detect 'zombie' jbossas instances

hosts.yml
Just a clean up - some scripts have .sh extension, some don't - harmonizing to have no .sh everywhere (for all ops scrips because they are designed to be command line tools - like ls, cp, and so on...).
This depends on [jboss-set-ci-scripts](https://github.com/jboss-set/hebe/commit/af1a3d4fb6b0b99224ff539a85a4a0b09c99c745) (1.2.4) which must released and installed first, before applying those changes.
=> remove .sh extension to match upcoming changes in jboss-set-ci-scripts

tasks/jenkins.yml, tasks/mjolnir.yml, tasks/prbz-overview.yml
If this PR is approve, the following changes will need to be done on Thunder:
```
```
JBoss EAP should pick up this change automatically - and the redeployments will be log in its logfile:
`# tail -f /var/log/jboss-eap/console.log`
(And update the [documentation](https://mojo.redhat.com/docs/DOC-1095681) which still mentions hardlink)
=> Switch from hard to soft links for webapp deployment

hosts.yml
The service script running gitlab is screwy and confuses Ansible, forcing to attempt to stop the service at each run. Thus I removed this checks. Gitlab has been disabled anyway, and unless somebody does fire it up, it won't come back on its own.
=> Remove checks on gitlab down

templates/nginx.conf.j2
Fix typo in config (missing ;) and removed unsupported option on nginx's thunder
=> SET-23 Set up a HTTP proxy cache for Maven Central on Thunder

hosts.yml, tasks/nginx.yml, templates/nginx.conf.j2, templates/nginx.maven.cache.conf.j2
Follow up work on the deployment of a HTTP cache on Thunder. As it turns out we need to cache several different repositories (maven central, jboss.org, but also some product specific repos), this PR does some cleanup and much needed generic handling.
=> SET-23 - Set up a HTTP proxy cache for Maven Central on Thunder

files/sudo-group-check.sh, hosts.yml, tasks/monit.yml
Issue: [SET-32](https://projects.engineering.redhat.com/browse/SET-32)
This change deploys a new script on Thunder that will check that each user defined in the sudoers.d folders belongs to the 'jboss-set' group, ensuring that user can indeed execute sudo command.
=> SET-32 - Makes monit checks that 'sudoers' user all belongs to the appropriate 'jboss-set' (local) group

hosts.yml
yum update needs to fetch metadata from download-ipv4.eng.brq.redhat.com which is not resolved on thunder.
```
[wangc@thunder ~]$ sudo yum update prbz-overview
Loaded plugins: product-id, rhnplugin, security, subscription-manager, versionlock
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Update Process
http://download-ipv4.eng.brq.redhat.com/released/JBEAP-7/latest-released/JBEAP-7.0-RHEL-6/Server/x86_64/os/repodata/repomd.xml: [Errno 12] Timeout on http://download-ipv4.eng.brq.redhat.com/released/JBEAP-7/latest-released/JBEAP-7.0-RHEL-6/Server/x86_64/os/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 …
```
=> add download-ipv4.eng.brq.redhat.com to system monitored by Monit

templates/monit.ping.j2
I saw a massive ping test failure and success of github.com ping test on 29 March 2018. https://post-office.corp.redhat.com/mailman/private/jboss-set-ops/2018-March/date.html
Monit network ping test does not configure a timeout. This adjust it to 15 seconds as per
> If no reply arrive within TIMEOUT seconds, Monit reports an error. If at least one reply was received, the ping test is considered a success.
in https://mmonit.com/monit/documentation/monit.html
=> adjust monit ping timeout

hosts.yml, tasks/monit.yml, templates/monit.remote.http.service.j2
- and removed github from the icmp checks
It seems that Github had disabled ICMP or simply that our infra had a hard time forwarding the request for a while, which lead to many false+ from monitoring. So I'm suggesting here to replace this checks (and maybe other) by a more high-level check using HTTP.
@soul2zimate @iweiss what do you think about it?
=> Add checks for remote HTTP services

templates/cron-cleaning-logs.j2
/opt/rh/eap7/root/usr/share/wildfly/standalone/log is actually a symlink so find refuses to follow it by default
=> Fix for cleaning old EAP logs

templates/harmonia-eap-build.j2
Allow to set custom job script in a way so harmonia behaves the same regardless if it is default value or custom.
=> Improve default value so it behaves the same for custom <---- 0_o

tasks/jboss-eap7.yml, templates/nginx.conf.j2
We need to expose development instance for mjolnir.
Incomplete: I don't know where to define the `mjolnir_dev_ds.*` properties for datasource. There are already equivalent properties for production instance...
=> Expose mjolnir dev instance

roles/jobs/templates/job-template.yml.j2
Issue: https://issues.redhat.com/browse/SET-389
This PR tries to add support to defin extra job parameters in Zeus.
=> [SET-389] Add ability to support defining extra job parameters

roles/jobs/defaults/main.yml, roles/jobs/templates/job-template.yml.j2
Issue: https://issues.redhat.com/browse/SET-393
This PR tries to add additional variable: `jenkinsfile.polling` default to `false` so that changes in cedalion won't trigger job execution.
This may be controversial if it should or not trigger the job execution, so adding this variable make it flexible to update job on demand.
=> [SET-393] Code changes in hera, harmonia, cedalion triggers all jobs on Olympus

roles/jenkins/defaults/main.yml, roles/jenkins/tasks/main.yml, roles/jenkins/templates/casc.yaml.j2, roles/jobs/templates/job-template.yml.j2
Add initial job-dsl job to Jenkins casc, fix Jenkins trustore.
Requires https://github.com/jboss-set/ares/pull/5, https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/37 and https://github.com/jboss-set/cedalion/pull/13
Note the csb-jenkinks-definitions repo can be moved to github - I'm not sure which repository though. Should we restructure cedalion for it? Or is it better to go with separate repo?
=> set up initial job for job-dsl

roles/java_certs/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-470
("include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in ansible version 2.16)
=> SET-470 include will be removed in ansible version 2.16

roles/java_certs/tasks/java_certs.yml, roles/java_certs/tasks/main.yml
@rpelisse can you review please?
Importing certs didn't work correctly because the `cacert_file` was being set by the first JDK and not updated later. Also importing Root CA properly (my MR from yesterday was wrong).
There's related MR in zeus-vars
=> Fix cacert path in java_cert and add Root CA

roles/ssh/tasks/known_hosts.yml, roles/ssh/tasks/main.yml
The repositories need to be added to the known_hosts for Jenkins git host verification to work correctly
@rpelisse could you review please?
=> Add repositories to known hosts

cci_casc_edit.yml, cci_run.yml
Issue: https://issues.redhat.com/browse/SET-570 
it can do the following ->
- Clone your forked [csb-jenkins-definition](https://gitlab.cee.redhat.com/jboss-set/csb-jenkins-definition) from gitlab.
- rebase it with changes with the upstream repo.
- Updated the newly formed image name 
- create the PR
Zeus vars PR: https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/80
=> SET-570 Automate updating CCI worker VMs in Gitlab.

molecule/java/vars.yml
Issue: https://issues.redhat.com/browse/SET-588
zeus-vars PR: https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/82
=> SET-588 maven 3.6.3 is not found inside downloads.apache.org

molecule/vault/converge.yml, molecule/vault/molecule.yml, molecule/vault/prepare.yml, molecule/vault/vars.yml, molecule/vault/vault.yml, molecule/vault/verify.yml, requirements.yml, roles/ssh/tasks/deploy.yml, roles/vault/defaults/main.yml, roles/vault/tasks/main.yml, roles/vault/tasks/vault-approle.yml, roles/vault/tasks/vault-token.yml
Issue: https://issues.redhat.com/browse/SET-651
This would be the first PR to add the support to read secrets from a specified HashiCorp Vault instance.
What it does are:
* Adds a role called `vault` to read secrets from specified paths in a HashiCorp Vault server. It uses the secret key as the Ansible variable name, and uses the secret value as the Ansbile variable value.
* The role supports both `token` and `approle` authentication method, depending on the environment set up, it will use different authentication approach.
* Adds `community.hashi_vault` to the requirements.yml file
* Update to `ssh` role to support writing ssh private key files from content besides copying from another file. This is because the private keys are secrets, and they need to be put somewhere in the HashiCorp …
=> [SET-651] Adds support to read secrets from HashiCorp Vault

cci_run.yml, cci_worker.yml, jenkins.yml, zeus.yml
Issue: https://issues.redhat.com/browse/SET-651
This is a follow up PR of https://github.com/jboss-set/zeus/pull/232.
This PR tries to enable `vault` role in the playbooks which may need access credential information.
* It makes sure the `hvac` python library installed according to the requirement from the [community.hashi_vault ansible collection](https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/docsite/user_guide.html#ansible-collections-community-hashi-vault-docsite-user-guide-requirements). 
* It assumes the vault related configurations are in `vars/vault.yml` file
* It has the `vault` role as the first task in the `pre_tasks` section to prepare needed sensitive values before other tasks.
=> [SET-651] Enable vault role in playbooks

molecule/account/molecule.yml, molecule/aphrodite/molecule.yml, molecule/bashrc/molecule.yml, molecule/cron/molecule.yml, molecule/fast_yum_install/molecule.yml, molecule/git/molecule.yml, molecule/hosts/molecule.yml, molecule/java/molecule.yml, molecule/kdump/molecule.yml, molecule/motd/molecule.yml, molecule/netrc/molecule.yml, molecule/qualys_fix/molecule.yml, molecule/vault/molecule.yml
Issue: https://issues.redhat.com/browse/SET-718
molecule issue discussion: https://github.com/ansible/molecule/issues/4140
=> SET-718 Fix Zeus molecule issue

roles/java_certs/tasks/java_certs.yml
Issue - https://issues.redhat.com/browse/SET-742
zeus-vars PR: https://gitlab.cee.redhat.com/jboss-set/zeus-vars/-/merge_requests/113
=> SET-742 Zeus: don't import specific service certificates into truststore

roles/cron/templates/ansible-daily-run.sh.j2
@spyrkob This should work betterly...
=> cron: rewrite ansible-daily-run script

cci_worker.yml, roles/cci_worker/tasks/main.yml
Issue: https://issues.redhat.com/browse/SET-722
=> SET-722 Refactor cci_worker to perform automation smoothly

roles/cci_worker/templates/settings.xml.j2
This helps with building productized projects that need access to Brew & MRRC, but don't have those repos configured in their pom.xml.
=> CCI worker settings.xml: add profile with product repositories

.github/workflows/ci.yml, molecule/account/molecule.yml, molecule/cron/molecule.yml
Issue: https://issues.redhat.com/browse/SET-771
=> SET-771 Implementing the CI fix

roles/cci_worker/files/containers.conf, roles/cci_worker/tasks/main.yml
https://issues.redhat.com/browse/SET-898
The short default timeout is suspected to cause broken pipe exceptions in the XP5 testsuite in tests that use testcontainers.
The containers.conf file is the default file currently present in the agent VMs, the only changed directive is the `service_timeout = 120`.
=> SET-898 Increase the podman-service timeout
